---
  - name: Install Apache and NodeJS
    hosts: devwebservers
    tasks:
      - name: Install Apache
        yum:
          name: apache2
          state: present
      - name: Install NodeJS
        yum:
          name: nodejs
          state: present
